from app.models import db, Like, environment, SCHEMA
from sqlalchemy.sql import text, insert


# Adds a demo user, you can add other users here if you want
def seed_likes():
    likes = [
        {"user_id": 1, "clip_id": 1, "is_like": True},
        {"user_id": 1, "clip_id": 2, "is_like": True},
        {"user_id": 1, "clip_id": 3, "is_like": True},
        {"user_id": 1, "clip_id": 4, "is_like": False},
        {"user_id": 1, "clip_id": 5, "is_like": True},
        {"user_id": 1, "clip_id": 6, "is_like": True},
        {"user_id": 1, "clip_id": 7, "is_like": True},
        {"user_id": 1, "clip_id": 8, "is_like": False},
        {"user_id": 1, "clip_id": 9, "is_like": True},
        {"user_id": 1, "clip_id": 10, "is_like": True},
        {"user_id": 1, "clip_id": 11, "is_like": True},
        {"user_id": 1, "clip_id": 12, "is_like": False},
        {"user_id": 1, "clip_id": 13, "is_like": False},
        {"user_id": 1, "clip_id": 14, "is_like": True},
        {"user_id": 1, "clip_id": 15, "is_like": True},
        {"user_id": 1, "clip_id": 17, "is_like": True},
        {"user_id": 1, "clip_id": 18, "is_like": False},
        {"user_id": 1, "clip_id": 19, "is_like": True},
        {"user_id": 1, "clip_id": 20, "is_like": True},
        {"user_id": 1, "clip_id": 21, "is_like": True},
        {"user_id": 1, "clip_id": 22, "is_like": False},                    
        {"user_id": 2, "clip_id": 1, "is_like": True},
        {"user_id": 2, "clip_id": 2, "is_like": True},
        {"user_id": 2, "clip_id": 3, "is_like": True},
        {"user_id": 2, "clip_id": 4, "is_like": False},
        {"user_id": 2, "clip_id": 5, "is_like": True},
        {"user_id": 2, "clip_id": 6, "is_like": True},
        {"user_id": 2, "clip_id": 7, "is_like": True},
        {"user_id": 2, "clip_id": 8, "is_like": False},
        {"user_id": 2, "clip_id": 9, "is_like": True},
        {"user_id": 2, "clip_id": 10, "is_like": True},
        {"user_id": 2, "clip_id": 12, "is_like": True},
        {"user_id": 2, "clip_id": 11, "is_like": False},
        {"user_id": 2, "clip_id": 13, "is_like": False},
        {"user_id": 2, "clip_id": 14, "is_like": True},
        {"user_id": 2, "clip_id": 15, "is_like": True},
        {"user_id": 2, "clip_id": 17, "is_like": True},
        {"user_id": 2, "clip_id": 18, "is_like": False},
        {"user_id": 2, "clip_id": 19, "is_like": True},
        {"user_id": 2, "clip_id": 20, "is_like": True},
        {"user_id": 2, "clip_id": 22, "is_like": True},
        {"user_id": 2, "clip_id": 23, "is_like": False},  
        {"user_id": 2, "clip_id": 24, "is_like": True},
        {"user_id": 2, "clip_id": 25, "is_like": True},
        {"user_id": 2, "clip_id": 26, "is_like": True},
        {"user_id": 2, "clip_id": 27, "is_like": False},
        {"user_id": 3, "clip_id": 1, "is_like": True},
        {"user_id": 3, "clip_id": 4, "is_like": False},
        {"user_id": 3, "clip_id": 6, "is_like": False},
        {"user_id": 3, "clip_id": 2, "is_like": True},
        {"user_id": 3, "clip_id": 8, "is_like": True},
        {"user_id": 3, "clip_id": 10, "is_like": True},
        {"user_id": 3, "clip_id": 12, "is_like": False},
        {"user_id": 3, "clip_id": 16, "is_like": True},
        {"user_id": 3, "clip_id": 17, "is_like": True},
        {"user_id": 3, "clip_id": 20, "is_like": True},
        {"user_id": 3, "clip_id": 23, "is_like": False},  
        {"user_id": 3, "clip_id": 22, "is_like": True},
        {"user_id": 3, "clip_id": 25, "is_like": True},
        {"user_id": 3, "clip_id": 26, "is_like": True},
        {"user_id": 3, "clip_id": 27, "is_like": False},
        {"user_id": 3, "clip_id": 28, "is_like": True},
        {"user_id": 3, "clip_id": 29, "is_like": True},
        {"user_id": 3, "clip_id": 3, "is_like": True},
        {"user_id": 3, "clip_id": 31, "is_like": False},
        {"user_id": 3, "clip_id": 11, "is_like": True},
        {"user_id": 3, "clip_id": 33, "is_like": True},    
        {"user_id": 4, "clip_id": 1, "is_like": True},
        {"user_id": 4, "clip_id": 5, "is_like": True},
        {"user_id": 4, "clip_id": 7, "is_like": True},
        {"user_id": 4, "clip_id": 9, "is_like": False},
        {"user_id": 4, "clip_id": 10, "is_like": True},
        {"user_id": 4, "clip_id": 16, "is_like": True},
        {"user_id": 4, "clip_id": 18, "is_like": True},
        {"user_id": 4, "clip_id": 20, "is_like": False},
        {"user_id": 4, "clip_id": 23, "is_like": True},
        {"user_id": 4, "clip_id": 25, "is_like": True},
        {"user_id": 4, "clip_id": 27, "is_like": True},
        {"user_id": 4, "clip_id": 29, "is_like": False},
        {"user_id": 4, "clip_id": 30, "is_like": False},
        {"user_id": 4, "clip_id": 32, "is_like": True},
        {"user_id": 4, "clip_id": 36, "is_like": True},  
        {"user_id": 5, "clip_id": 2, "is_like": True},
        {"user_id": 5, "clip_id": 3, "is_like": True},
        {"user_id": 5, "clip_id": 4, "is_like": False},
        {"user_id": 5, "clip_id": 5, "is_like": True},
        {"user_id": 5, "clip_id": 6, "is_like": True},
        {"user_id": 5, "clip_id": 7, "is_like": True},
        {"user_id": 5, "clip_id": 8, "is_like": False},
        {"user_id": 5, "clip_id": 9, "is_like": True},
        {"user_id": 5, "clip_id": 10, "is_like": True},
        {"user_id": 5, "clip_id": 11, "is_like": True},
        {"user_id": 5, "clip_id": 12, "is_like": False},
        {"user_id": 5, "clip_id": 13, "is_like": False},
        {"user_id": 5, "clip_id": 14, "is_like": True},
        {"user_id": 5, "clip_id": 15, "is_like": True},    
        {"user_id": 6, "clip_id": 2, "is_like": True},
        {"user_id": 6, "clip_id": 4, "is_like": True},
        {"user_id": 6, "clip_id": 7, "is_like": False},
        {"user_id": 6, "clip_id": 9, "is_like": True},
        {"user_id": 6, "clip_id": 11, "is_like": True},
        {"user_id": 6, "clip_id": 13, "is_like": True},
        {"user_id": 6, "clip_id": 1, "is_like": False},
        {"user_id": 6, "clip_id": 16, "is_like": True},
        {"user_id": 6, "clip_id": 19, "is_like": True},
        {"user_id": 6, "clip_id": 20, "is_like": True},
        {"user_id": 6, "clip_id": 21, "is_like": False},
        {"user_id": 6, "clip_id": 22, "is_like": False},
        {"user_id": 6, "clip_id": 26, "is_like": True},
        {"user_id": 6, "clip_id": 28, "is_like": True},        
        {"user_id": 7, "clip_id": 2, "is_like": True},
        {"user_id": 7, "clip_id": 3, "is_like": True},
        {"user_id": 7, "clip_id": 4, "is_like": False},
        {"user_id": 7, "clip_id": 5, "is_like": True},
        {"user_id": 7, "clip_id": 6, "is_like": True},
        {"user_id": 7, "clip_id": 7, "is_like": True},
        {"user_id": 7, "clip_id": 8, "is_like": False},
        {"user_id": 7, "clip_id": 9, "is_like": True},
        {"user_id": 7, "clip_id": 10, "is_like": True},
        {"user_id": 7, "clip_id": 11, "is_like": True},
        {"user_id": 7, "clip_id": 12, "is_like": False},
        {"user_id": 7, "clip_id": 13, "is_like": False},
        {"user_id": 7, "clip_id": 14, "is_like": True},
        {"user_id": 7, "clip_id": 15, "is_like": True},       
        {"user_id": 8, "clip_id": 12, "is_like": True},
        {"user_id": 8, "clip_id": 13, "is_like": True},
        {"user_id": 8, "clip_id": 14, "is_like": False},
        {"user_id": 8, "clip_id": 15, "is_like": True},
        {"user_id": 8, "clip_id": 16, "is_like": True},
        {"user_id": 8, "clip_id": 17, "is_like": True},
        {"user_id": 8, "clip_id": 18, "is_like": False},
        {"user_id": 8, "clip_id": 19, "is_like": True},
        {"user_id": 8, "clip_id": 20, "is_like": True},
        {"user_id": 8, "clip_id": 21, "is_like": True},
        {"user_id": 8, "clip_id": 22, "is_like": False},
        {"user_id": 8, "clip_id": 23, "is_like": False},
        {"user_id": 8, "clip_id": 24, "is_like": True},
        {"user_id": 8, "clip_id": 25, "is_like": True},    
        {"user_id": 9, "clip_id": 1, "is_like": True},
        {"user_id": 9, "clip_id": 16, "is_like": True},
        {"user_id": 9, "clip_id": 12, "is_like": False},
        {"user_id": 9, "clip_id": 10, "is_like": True},
        {"user_id": 9, "clip_id": 17, "is_like": True},
        {"user_id": 9, "clip_id": 7, "is_like": True},
        {"user_id": 9, "clip_id": 3, "is_like": False},
        {"user_id": 9, "clip_id": 9, "is_like": True},
        {"user_id": 9, "clip_id": 20, "is_like": True},
        {"user_id": 9, "clip_id": 21, "is_like": True},
        {"user_id": 9, "clip_id": 22, "is_like": False},
        {"user_id": 9, "clip_id": 23, "is_like": False},
        {"user_id": 9, "clip_id": 34, "is_like": True},
        {"user_id": 9, "clip_id": 35, "is_like": True},      
        {"user_id": 10, "clip_id": 22, "is_like": True},
        {"user_id": 10, "clip_id": 23, "is_like": True},
        {"user_id": 10, "clip_id": 24, "is_like": False},
        {"user_id": 10, "clip_id": 25, "is_like": True},
        {"user_id": 10, "clip_id": 26, "is_like": True},
        {"user_id": 10, "clip_id": 27, "is_like": True},
        {"user_id": 10, "clip_id": 28, "is_like": False},
        {"user_id": 10, "clip_id": 29, "is_like": True},
        {"user_id": 10, "clip_id": 30, "is_like": True},
        {"user_id": 10, "clip_id": 31, "is_like": True},
        {"user_id": 10, "clip_id": 32, "is_like": False},
        {"user_id": 10, "clip_id": 33, "is_like": False},
        {"user_id": 10, "clip_id": 34, "is_like": True},
        {"user_id": 10, "clip_id": 35, "is_like": True},            
        {"user_id": 11, "clip_id": 1, "is_like": True},
        {"user_id": 11, "clip_id": 3, "is_like": True},
        {"user_id": 11, "clip_id": 4, "is_like": False},
        {"user_id": 11, "clip_id": 6, "is_like": True},
        {"user_id": 11, "clip_id": 8, "is_like": True},
        {"user_id": 11, "clip_id": 9, "is_like": True},
        {"user_id": 11, "clip_id": 13, "is_like": False},
        {"user_id": 11, "clip_id": 14, "is_like": True},
        {"user_id": 11, "clip_id": 16, "is_like": True},
        {"user_id": 11, "clip_id": 19, "is_like": True},
        {"user_id": 11, "clip_id": 23, "is_like": False},
        {"user_id": 11, "clip_id": 34, "is_like": False},
        {"user_id": 11, "clip_id": 36, "is_like": True},
        {"user_id": 11, "clip_id": 35, "is_like": True},    
        {"user_id": 12, "clip_id": 2, "is_like": True},
        {"user_id": 12, "clip_id": 3, "is_like": True},
        {"user_id": 12, "clip_id": 4, "is_like": False},
        {"user_id": 12, "clip_id": 5, "is_like": True},
        {"user_id": 12, "clip_id": 6, "is_like": True},
        {"user_id": 12, "clip_id": 7, "is_like": True},
        {"user_id": 12, "clip_id": 8, "is_like": False},
        {"user_id": 12, "clip_id": 9, "is_like": True},
        {"user_id": 12, "clip_id": 10, "is_like": True},
        {"user_id": 12, "clip_id": 11, "is_like": True},
        {"user_id": 12, "clip_id": 12, "is_like": False},
        {"user_id": 12, "clip_id": 13, "is_like": False},
        {"user_id": 12, "clip_id": 14, "is_like": True},
        {"user_id": 12, "clip_id": 15, "is_like": True},   
        {"user_id": 12, "clip_id": 1, "is_like": True},
        {"user_id": 12, "clip_id": 16, "is_like": True},
        {"user_id": 12, "clip_id": 17, "is_like": False},
        {"user_id": 12, "clip_id": 18, "is_like": True},
        {"user_id": 12, "clip_id": 19, "is_like": True},
        {"user_id": 12, "clip_id": 20, "is_like": True},
        {"user_id": 12, "clip_id": 21, "is_like": False},
        {"user_id": 12, "clip_id": 22, "is_like": True},
        {"user_id": 12, "clip_id": 23, "is_like": True},
        {"user_id": 12, "clip_id": 24, "is_like": True},
        {"user_id": 12, "clip_id": 25, "is_like": False},
        {"user_id": 12, "clip_id": 26, "is_like": False},
        {"user_id": 12, "clip_id": 27, "is_like": True},
        {"user_id": 12, "clip_id": 28, "is_like": True},      
        {"user_id": 12, "clip_id": 29, "is_like": False},
        {"user_id": 12, "clip_id": 30, "is_like": True},
        {"user_id": 12, "clip_id": 31, "is_like": True},
        {"user_id": 12, "clip_id": 32, "is_like": True},
        {"user_id": 12, "clip_id": 33, "is_like": False},
        {"user_id": 12, "clip_id": 34, "is_like": False},
        {"user_id": 12, "clip_id": 35, "is_like": True},
        {"user_id": 12, "clip_id": 36, "is_like": True},                                                                                  
    ]

    db.session.execute(insert(Like), likes)
    db.session.commit()


# Uses a raw SQL query to TRUNCATE or DELETE the users table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_likes():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.likes RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM likes"))
        
    db.session.commit()
