"""empty message

Revision ID: d34124e92dc9
Revises: e2ba2db1ac58
Create Date: 2024-06-13 20:09:49.886973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd34124e92dc9'
down_revision = 'e2ba2db1ac58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.alter_column('caption',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.alter_column('caption',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
