"""empty message

Revision ID: e2ba2db1ac58
Revises: 91394f2b328b
Create Date: 2024-06-11 02:58:58.093286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ba2db1ac58'
down_revision = '91394f2b328b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.drop_column('is_private')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
